name: build-image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  RELEASE_VERSION: 6.10.1 ## BlockScout Release version

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      IMAGE_TAG: ${{ github.event.repository.name }}-${{ inputs.environment }}
    outputs:
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tagging
        id: tagging
        run: |
          echo "GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Build Frontend
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          file: ./Dockerfile  # frontend를 위한 Dockerfile 경로로 변경 필요
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPO }}:${{ env.IMAGE_TAG }}-${{ steps.tagging.outputs.GIT_SHA }}-frontend,${{ env.ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPO }}:${{ env.IMAGE_TAG }}-frontend-latest
          platforms: linux/amd64
          build-args: |
            GIT_COMMIT_SHA=${{ env.GIT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}