name: trigger
on:
  push:
    tags:
      - '*dev*'
      - '*release*'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'jest/**'
      - 'playwright/**'
      - 'tools/**'

permissions:
  id-token: write
  contents: read
jobs:
  dev-deploy:
    if: contains(github.ref, '-dev')
    uses: ./.github/workflows/common.yml
    with:
      environment: dev
    secrets: inherit

  release-deploy:
    if: contains(github.ref, '-release')
    uses: ./.github/workflows/common.yml
    with:
      environment: prod
    secrets: inherit